<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="AutoMapper" Version="14.0.0" />
		<PackageReference Include="Microsoft.AspNetCore.Http.Abstractions" Version="2.3.9" />
		<PackageReference Include="Microsoft.Data.SqlClient" Version="7.0.0" />
		<PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.5" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="10.0.5" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.5" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.5">
		  <PrivateAssets>all</PrivateAssets>
		  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="10.0.5" />
		<PackageReference Include="Microsoft.Extensions.Http" Version="10.0.5" />
		<PackageReference Include="StackExchange.Redis" Version="2.12.4" />
		<PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="10.0.5" />
		<PackageReference Include="Microsoft.Extensions.Caching.StackExchangeRedis" Version="10.0.5" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\..\BuildingBlocks\MyApp.BuildingBlocks.Application\MyApp.BuildingBlocks.Application.csproj" />
		<ProjectReference Include="..\..\..\BuildingBlocks\MyApp.BuildingBlocks.Infrastructure\MyApp.BuildingBlocks.Infrastructure.csproj" />
		<ProjectReference Include="..\..\..\IntegrationContracts\MyApp.IntegrationContracts.csproj" />
		<ProjectReference Include="..\MyApp.Modules.Transport.Application\MyApp.Modules.Transport.Application.csproj" />
	</ItemGroup>
</Project>
