<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="Orders\**" />
    <EmbeddedResource Remove="Orders\**" />
    <None Remove="Orders\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MediatR" Version="14.0.0" />
    <PackageReference Include="FluentValidation" Version="12.1.1" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.1" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Abstractions\Outbox\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MyApp.BuildingBlocks.Domain\MyApp.BuildingBlocks.Domain.csproj" />
  </ItemGroup>
</Project>
